GOOGLE_URL= "https://wf.wapice.com/"
GLOBAL_RETRY_AMOUNT= "3x"
GLOBAL_RETRY_INTERVAL= "1.0s"
EXCEL_FILE_LOCATION= "C:\\Users\\saktuo\\Desktop\\WF_emails.xlsx"
POWERSHELL_SCRIPT= "C:\\Users\\saktuo\\Desktop\\send_email"
SC_POWERSHELL= "ps_sc.png"
