*** Settings ***
Documentation   Sending email via Gmail
Library         ExampleLibrary
Library         RPA.Email.ImapSmtp    smtp_server=smtp.gmail.com    smtp_port=587
Variables       variables.py

*** Tasks ***
Send test email
    Authorize    account=${USER_NAME}    password=${PASSWORD}
    Send Message    sender=${USERNAME}
    ...    recipients=${RECIPIENT}
    ...    subject=Message generated by robot
    ...    body=Hello! Have a nice day


